### ISSUE TITLE
jquery and jquery datatables loaded twice, also unminified

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/clarin-curation-module#47]
I noticed that in the web pages of Curation 3.0, the jquery and datatable js files are loaded twice, both in minified and non-minified form.

from the page source:
```
...
   <!-- #wrapper-footer-full --> 
  </div> 
  <script type="text/javascript" src="/view/fundament/vendor/jquery/jquery.min.js"></script> 
  <script type="text/javascript" src="/view/fundament/js/fundament.min.js"></script> 
  <script type="text/javascript" src="/view/js/dropzone.min.js"></script> 
  <script type="text/javascript" src="/view/js/curate.js"></script> 
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script> 
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script> 
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script> 
  <script type="text/javascript" src="https://cdn.datatables.net/fixedheader/3.1.5/js/dataTables.fixedHeader.min.js"></script> 
...
```

Note that there is both `src="https://code.jquery.com/jquery-3.3.1.js"` and `src="/view/fundament/vendor/jquery/jquery.min.js"`
and both `src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"` and `src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"`

**Comment by wowasa** [comment]
corrected in release 3.1.1 which I'm going to deploy at 19h

**Comment by twagoo** [comment]
<img width="1239" alt="Screenshot 2019-08-14 at 14 34 12" src="https://user-images.githubusercontent.com/7011396/63018082-aabbf400-bea0-11e9-98e3-47035c019c53.png">

this still occurs when visiting https://curate.acdh.oeaw.ac.at (2019-08-14 11:35 UTC, Firefox 68.0.1)

**Comment by coy123** [comment]
Fixed in development branch
